<?php
include ("PalmDatabase.php");
include ("PalmDatabase_Properties.php");
include ("PalmDatabase_Record.php");
include ("PalmDatabase_Attributes.php");
include ("PalmDatabase_RecordAttributes.php");
include ("Mobi.php");
include ("lz77.php");
$test = new Mobi("testbook.mobi");
echo "Database name: " . $test->properties->name . "\n";
echo "Database records: " . count($test->records) . "\n";
echo "Attributes" . "\n";
echo "  Read-only: " . $test->properties->attributes->readonly . "\n";
echo "  Dirty Appinfo Area: " . $test->properties->attributes->dirtyAppInfoArea . "\n";
echo "  Backup: " . $test->properties->attributes->backup . "\n";
echo "  Install new version: " . $test->properties->attributes->install_newer . "\n";
echo "  Force reset: " . $test->properties->attributes->force_reset . "\n";
echo "  No beaming: " . $test->properties->attributes->no_beaming . "\n";
echo "Record attributes \n";
echo "Compression type: " . $test->compression . "\n";
echo "Header length: " . $test->records[0]->size . "\n";
echo "Header length % 4: " . $test->records[0]->size % 4 . "\n";
var_dump($test->records[3]);
